### ISSUE TITLE
Opnemen beeldmateriaal van ovaal en buiten

### ISSUE THREAD

**Issue by IIsaku** [urbinn/urbinn#104]
- [ ] Opname Ovaal (1 loop closure)
- [x] Opname buiten (1 loop closure)

**Comment by Viradj** [comment]
Opname van buiten, er zijn twee opnames gekomen. Deze opnames bevatten beiden 1 loop closure.

**Comment by Viradj** [comment]
Besloten om de buiten opnames niet te doen.
