### ISSUE TITLE
Orb2 stability fix

### ISSUE THREAD

**Issue by Eyegi** [urbinn/urbinn#107]
- [x] Memory leaks
- [x] Inlezen bin file incrementeel leren

**Comment by jvhoven** [comment]
Misschien is het handig om de punten op te splitsen; incrementeel leren in een aparte ticket omdat dit meer werk bevat en makkelijker te documenteren is per taak.

**Comment by Eyegi** [comment]
Biggest bugs have been fixed.
Orb runs on rugzak dataset without crashing.
Also did 2 runs on outside dataset no crashing but results not checked.
