### ISSUE TITLE
URB: Local Mapping

### ISSUE THREAD

**Issue by jvhoven** [urbinn/urbinn#110]
- [ ] ~Keyframe diepte punten update~
- [ ] Mappoints culling
- [ ] Keyframes maken
- [ ] Spanning tree visible keyframes

**Comment by jeroenvuurens** [comment]
Bij nader inzien wordt de diepte van punten op een keyframe niet geüpdatet, maar via local BA wordt de diepte beter geschat.

**Comment by jeroenvuurens** [comment]
map point culling op basis van punten die in geen enkel van de N vervolg frames worden gedetect?

**Comment by jeroenvuurens** [comment]
Dit is een oud ticket. We hebben MapPoints verminderd door alleen punten over te houden waarvoor een confident stereo-estimation bestaat, of een match is met een punt op een vorig keyframe waarvoor een confident stereo estimation bestaat. 

Voor een nieuwe frame wordt een pose geschat door te vergelijken met het laatste keyframe. Er wordt een nieuw KeyFrame gemaakt van het vorige frame (dat nog geen keyframe is) als er geen betrouwbare pose kan worden gemaakt voor een nieuw frame. Er kan geen pose worden gemaakt als er minder dan 10 punten over zijn, of als de snelheid of rotatie van de pose een gekke waarde teruggeeft.

Spanning Tree van visible Keyframes is niet geïmplementeerd, maar er is wel een functie om covisible keyframes op te vragen.
