### ISSUE TITLE
URB: Evaluatie Pointcloud

### ISSUE THREAD

**Issue by jvhoven** [urbinn/urbinn#112]
Het idee is om de eerste 40 frames van Kitti door URB heen te halen en vervolgens de volgende stappen uit te voeren:

- [X] Vergelijken met pose graph orb2 #113
- [ ] Pose graph op google maps leggen (voor de dataset buiten HHS)

**Comment by jeroenvuurens** [comment]
Poses vergeleken. Verschil tussen ORB en URB pose graph blijkt heel klein. Elk frame in Sequence 00 is ca. 70-73 cm. Verschil tussen ORB en URB over 20 meter is ca. 40cm.
