### ISSUE TITLE
Plan opnames Delft: Uitzoeken GPS

### ISSUE THREAD

**Issue by jvhoven** [urbinn/urbinn#115]
Het idee is om per afbeelding ook GPS data op te nemen. De vraag is alleen hoe we dit willen doen. De volgende theorieën kunnen onderzocht worden:

- [x] Onderzoeken bestaande technieken
- [x] Bv via mobiele app gekoppeld aan laptop

**Comment by M4dmuffin** [comment]
GPS Logger App - Google Play.
https://play.google.com/store/apps/details?id=eu.basicairdata.graziano.gpslogger&hl=nl

Pros:
- Real time logger GPS coordinates
- Timestamps
- Export KML, GPX, and TXT format 
- View trips  in Google Earth (if installed) 
- The app is 100% Free and Open Source.
- Visualization of current GPS information
- Manual Altitude Correction (add an overall offset to your track)

**Comment by M4dmuffin** [comment]
Indien de timestamps van GPS Logger niet goed gematched kunnen worden aan de opnames (of onbetrouwbaar zijn) dan kan wellicht gebruik gemaakt worden van HoudahGeo  https://www.houdah.com/houdahGeo/

HoudahGeo stores latitude, longitude and altitude as geotags right within the image file. Just like a GPS-enabled camera.

cons:
- Single User License $34,-

**Comment by NektariosEvangelou** [comment]
Hierbij besloten dat er geen gebruik zal worden gemaakt van GPS als evaluatie en eventuele latere correctie.
