### ISSUE TITLE
Evaluatie self trained YOLO

### ISSUE THREAD

**Issue by chrisros** [urbinn/urbinn#116]
evaluatie self trained YOLO met eigen labels
133 classes

trainigset heeft gedraaid
evaluatie op 7300-7480

**Comment by NektariosEvangelou** [comment]
@chrisros Kan jij vandaag de evaluatie voltooien en de resultaten in dit ticket plaatsen?

**Comment by chrisros** [comment]
Evaluatie set van de 250000weights is te vinden in: 
`datascience.hhs.nl:/data/urbinn/darknet/output/250_weights/`

**Comment by chrisros** [comment]
ik ga de set over alle weights in increments van 10K draaien (10k, 20k ... 250k) zodat we wat kunnen zeggen over wanneer een model voldoende getrained is.
