### ISSUE TITLE
Evaluatie 133 classes / batch

### ISSUE THREAD

**Issue by chrisros** [urbinn/urbinn#117]
Evaluatie van de trining progressie / recall per 10000

**Comment by chrisros** [comment]
Afbeelding uploaden werkt niet dus hier de grafiek: https://imgur.com/a/g6Nad

Yolo training op datascience server voor het weekend gestart d.m.v. script:
`/data/urbinn/darknet/train_ownlabels`

Dit script maakt gebruik van de config files uit de volgende map:
`/data/urbinn/darknet/own_cfg/`

De output van de training (de weights, opgeslagen per 10000) zijn te vinden in: 
`/data/urbinn/darknet/kitti_own_labels_0612/`

Deze weights zijn gebruikt als input voor het 'batch_validate' script:
`/data/urbinn/darknet/batch_validate.py`

Dit script draaide een validatie run voor elke weights file in '/data/urbinn/darknet' en creerde daarvoor een map met corresponderende naam in:
`/data/urbinn/darknet/output/batch/`

Elk van deze mappen bevat een 'objects.json'  met daarin per foto de herkende objecten, deze zijn gebruikt als input van mijn notebook: 
https://datascience.hhs.nl:8888/user/14044943/notebooks/yolo-validation/Validation_IOU_Batch.ipynb

deze notebook haalt per ' foto'  uit objects.json de herkende bounding-boxes op, en vergelijkt deze met de gegevens uit de ground truth, te vinden in:
`/data/urbinn/darknet/gtconverted/`

De resultaten van deze evalutatie zijnte zien in:  https://imgur.com/a/g6Nad

Voor deze validatie is een IOU van .3 gebruikt omdat er nogsteeds iets niet helemaal lekker lijkt te gaan met het tekenen van de bounding boxes

**Comment by jeroenvuurens** [comment]
Wat staat er op de x-as?

**Comment by jeroenvuurens** [comment]
Het notebook is not accessible voor anderen

**Comment by chrisros** [comment]
De x-as is af te lezen als je op de afbeelding drukt..

Ik begrijp dat het notebook niet accesible is voor anderen, ik zal m ook op de server plaatsen

**Comment by chrisros** [comment]
Notebook staat op de server:

`/data/urbinn/darknet/Validation_IOU_Batch.ipynb`

**Comment by jeroenvuurens** [comment]
Als ik het goed heb, heb je het model getraind op alle images met een .txt in img, en gebruik je vervolgens 29 images van 7300+ met een .txt file voor de evaluatie. Als dat zo is, dan is 29 images voor de evaluatie te weinig, en dan heb je bovendien de validatie set gebruikt in je training? Of zie ik het verkeerd?

**Comment by jeroenvuurens** [comment]
Grafiek duidt erop dat je niet tot 250.000 hoeft door te leren om een goede indicatie te krijgen. Op 30k images krijg je al een redelijk beeld.
