### ISSUE TITLE
Evaluatie handmatig nameten afstanden

### ISSUE THREAD

**Issue by jvhoven** [urbinn/urbinn#124]

**Comment by M4dmuffin** [comment]
Er zijn meerdere foto's genomen vanuit verschillende hoeken en afstanden. Bij de laatste foto (foto4) zijn de afstanden direct nagemeten aan de hand van de urbs die gedetecteerd zijn. Deze afstanden lijken aardig te kloppen echter sommige orb afstanden wijken af van de werkelijke afstand. Tevens wanneer de afstanden groter worden blijkt het foutpercentage in centimeters toe te nemen.
