### ISSUE TITLE
Labelen evaluatie set Kitti

### ISSUE THREAD

**Issue by chrisros** [urbinn/urbinn#129]
Labelen set voor evalutatie self_trained 
kitti left 7300-7480

**Comment by NektariosEvangelou** [comment]
Kevin labelt foto's 7300 - 7390 en Nektarios labelt foto's 7391 - 7480

**Comment by NektariosEvangelou** [comment]
Nektarios foto's 7391 - 7480 zijn afgerond. Deze worden voor nu ook in de Google Drive geplaatst: https://drive.google.com/drive/folders/1Ro82hWVQxfpAZPxBcdiRlNFNz_YjjSp6
