### ISSUE TITLE
Urb plot trajectory

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#131]
Maak in Urb van een sequence van frame een plot van de afgelegde trajectory. Elk keyframe heeft een pose t.o.v. het vorige keyframe. Je kunt ook een pose berekenen t.o.v. frame[0]. 

Ik denk dat je opencv het beste kun gebruiken om het te tekenen. Een alternatief op opencv is de ORB2 aanpak. Transformeer alle bestaande punten door te vermenigvuldigen met de pose van het nieuwe keyframe en plot het nieuwe keyframe op (0,0,0).

**Comment by NektariosEvangelou** [comment]
In jupyterhub de notebook plot_trajectory aangemaakt, deze is terug te vinden onder /notebooks/urbinn/urb/trajectory/plot_trajectory.ipynb. Er is een stuk code geschreven om te kijken of we met 3 keyframes een trajectory kunnen tekenen met behulp van opencv. Het enige waar we nu tegenaan lopen is dat, wanneer wij de grafiek willen plotten het de volgende error geeft:

error: /feedstock_root/build_artefacts/opencv_1495918814239/work/opencv-3.2.0/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

Dit moet worden opgelost door libgtk2.0-dev en pkg-config te installeren. Tevens moet cmake re-runned worden of de configure script in function cvShowImage.
