### ISSUE TITLE
Plan van Delft uitvoeren

### ISSUE THREAD

**Issue by NektariosEvangelou** [urbinn/urbinn#133]
Het plan voor de opnames van Delft kan uitgevoerd worden. Hiervoor moet er kort van tevoren gekeken worden (voor het schieten van de beelden) of er geen neerslag is. Tevens moet Chris ervan op de hoogte zijn wanneer de beelden gemaakt gaan worden, want hij is degene met de auto. 

Benodigdheden:
- Auto (Chris)
- ZED Camera (Balie)
- Ducktape
- Externe HDD (Bob of Chris)
- Stroom? 
- Laptop (Viradj)
- USB Extender
- Planning
- Route

**Comment by Viradj** [comment]
Opnames zijn genomen, maar geen van deze zijn op basis van het plan dat is gemaakt. Dit komt omdat enkele wegen afgezet waren. 
In totaal zijn er drie verschillende routes opgenomen. 
/data/urbinn/datasets/Delft_route_1/
