### ISSUE TITLE
Een centrale repository maken van Pyurb en g2o

### ISSUE THREAD

**Issue by NektariosEvangelou** [urbinn/urbinn#134]
Er moet een centrale repository op GitHub gemaakt worden waar PyUrb en G2O samen erin terug te vinden zijn. Hiermee kan iedereen erbij.

**Comment by jeroenvuurens** [comment]
repo is klaar. de Rebo heet pyurb en staat onder de urbinn organisation op GitHub. In Pyurb staat een map bundleadjustment met de motion-only en local BA code. Als je ./compile runt (zie README) dan wordt de C++ code gebuild en de lib met Python bindings op de juste plek gezet. In de folder pyurb staan de Python libraries en in notebooks een aantal notebook experimenten. De notebooks moeten nog worden gecleaned, voor nu werken allen match_sequence2.ipynb en plot_trajectory_urb.ipynb.

**Comment by jeroenvuurens** [comment]
Iedereen kan een clone maken van de repo op de server, of lokaal in de docker. Maak svp een branch om in te werken.
