### ISSUE TITLE
Handmatig bepalen welke frame overlappen op Sequence 07 KITTI

### ISSUE THREAD

**Issue by NektariosEvangelou** [urbinn/urbinn#137]
Handmatig bepalen welke frame overlappen op Sequence 07 KITTI. Noteer alle frames die mogelijke overlapping hebben met elkaar, kijk vooral bij het begin en het einde die je in de trajectory terug kan zien.

**Comment by jeroenvuurens** [comment]
komt te vervallen als ticket 147 klaar is
