### ISSUE TITLE
URB uitbreiden

### ISSUE THREAD

**Issue by NektariosEvangelou** [urbinn/urbinn#140]
URB moet uitgebreid worden door middel van in de MapPoint het opnemen van de YOLO herkenningen.

**Comment by jvhoven** [comment]
Een experiment opgezet om buiten de structuur het voor elkaar te krijgen om punten te vinden in YOLO bounding boxes. Het experiment is [hier](https://github.com/urbinn/urb/blob/feature/yolo/experiments/yolo.ipynb) te vinden. 

Er is wel een probleem dat de bounding boxes niet "netjes" worden getekend waardoor sommige punten er binnen vallen die eigenlijk niet op de classificatie getekend worden.

**Comment by jvhoven** [comment]
Classificaties die YOLO gevonden hebben kunnen ingeladen worden bij het aanmaken van de frame objecten. Bekijk `experiments/yolo-sequence` voor meer details.
