### ISSUE TITLE
1. Introduction

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#152]
schrijven
- [x] paragraaf over de toepassingen waarvoor semantic mapping interessant is (maatschappelijk belang)
- [x] paragraaf over Urbinn project
- [x] paragraaf over semantic mapping (SLAM, sensoren, ROS e.d.)
- [x] paragraaf over tekortkomingen huidige aanpakken
- [x] paragraaf over bijdrage van dit paper

**Comment by NektariosEvangelou** [comment]
Introductie voor het paper is beknopt geschreven in Google Docs https://docs.google.com/document/d/1Fu9vlbC-m9wdtsd2AAghLuwDo25qq62BVia98RoEi_4/edit# 

De punten die geschreven moesten worden volgens dit issue, zijn ook uitgewerkt om zelf later te bepalen of het belangrijk is om dit in de introductie te bespreken. 

Het enige wat nog gedaan moet worden is het toevoegen van referenties, maar dit wordt gedaan bij de overgang van Google Docs naar  Latex.
