### ISSUE TITLE
2. Related Work

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#153]
- [x] Korte beschrijving SLAM, ref naar paper Davison. Korte beschrijving stappen SLAM, ref naar papers. Korte beschrijving bundle adjustment en landmark detection.
- [x] korte beschrijving state of the art: ORB2, LSD en VSO.
- [x] korte beschrijving state of the art op het gebied van object detection: YOLO en nog een aanpak
- [x] related work op het gebied van semantic mapping
- [x] beschrijven waarin onze aanpak verschilt van bestaande aanpakken.

**Comment by NektariosEvangelou** [comment]
Onderdeel is af en te vinden in Google Drive, https://docs.google.com/document/d/1Fu9vlbC-m9wdtsd2AAghLuwDo25qq62BVia98RoEi_4/edit#
