### ISSUE TITLE
serie foto's als test case

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#19]
op tafel, neutrale achtergrond, 2 rubiks kubussen, om de 10cm een foto. locatie kubussen en tafel meten.

**Comment by jeroenvuurens** [comment]
opnieuw maken met statief en kleinere afstand zodat plaatjes meer overlap hebben

**Comment by M4dmuffin** [comment]
reminder Kevin: cube, statief en camera meenemen
