### ISSUE TITLE
Camera Calibratie

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#34]
Voor accurate mapping is het nodig om de calibratie data voor de gebruikte camera te berekenen. Er bestaan blijkbaar tools voor calibratie voor PTAM die soms gebruikt worden: http://wiki.ros.org/ethzasl_ptam/Tutorials/camera_calibration verder uitzoeken hoe we een camera kunnen calibreren.

**Comment by chrisros** [comment]
http://ros-developer.com/2017/04/23/camera-calibration-with-ros/
vanuit: https://www.youtube.com/watch?v=yAYqt3RpT6c

**Comment by chrisros** [comment]
Met de bovengenoemde how-to moet het lukken een calibratie file te genereren.

**Comment by chrisros** [comment]
Eerste testcase is te vinden in het mapje stereocam_2017_09_20:
Calibratiefile + fotos uit set up
