### ISSUE TITLE
Camera inventariseren

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#38]
Camera regelen voor opnames. Iemand een high fps camera thuis? Mediatheek? Anders die van Pepper lenen.

**Comment by chrisros** [comment]
* Camera van Pepper alleen geschikt voor dichtbij.
* Kinect camera van @M4dmuffin (Kevin) heeft verloop kabel nodig (is besteld, en nagevraagd bij Inovation playground).
* Webcam geleend bij mediatheek, mediatheek beschikt niet over live/stero camera's zaosl de BumbleBee of the grashopper.
