### ISSUE TITLE
Metrics voor evaluatie point cloud

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#42]
Uitzoeken hoe we de kwaliteit van de geleerde point-cloud kunnen evalueren. Kijken in bestaande studies welke ground-truth en metrics worden gebruikt.

**Comment by jvhoven** [comment]
Er is een interessante paper gevonden over een aanpak voor de evaluatie van de point cloud, namelijk http://www.diva-portal.org/smash/get/diva2:459937/FULLTEXT02. Daarnaast is er een document (Google Drive -> Issues -> 42 - Evaluatie Point Cloud) opgesteld waarin meerdere aanpakken vanuit bestaande papers staan.
