### ISSUE TITLE
Evaluatieplan Slinger

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#43]
Stel een evaluatieplan op voor de Slinger dataset. Hoe wordt de ground truth gemaakt (bv meten bepaalde punten, bepaalde markers neerzetten, vergelijken map slinger, variantie locatie zelfde objecten tussen geleerde runs vergelijken).

**Comment by BobvanElburg** [comment]
Opzet gemaakt. Te vinden op Google drive.
