### ISSUE TITLE
Paper Object Detection Selecteren

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#49]
Volgende week woensdag hebben we de mogelijkheid voor een close reading sessie. Daarvoor moeten we van tevoren een paper uitzoeken. Voor de volgende sprint is het doel om te detecteren waar objecten in beeld staan. Het is nog niet belangrijk om het object te classificeren (is het een auto of voetganger). Het kan wel handig zijn om objecten te kunnen tracks (dus in een sequence van beelden zien dat het object zich verplaatst). http://www.cvlibs.net/datasets/kitti/eval_object.php

**Comment by M4dmuffin** [comment]
op Google Drive in de map documentatie staat een map 'Real Time Object detection'. Hierin staat een aantal papers en in het Word document de links naar de Open source projecten
