### ISSUE TITLE
Kijken hoe evaluatie TUM is gedaan

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#52]
Maak een voorbeeld van hoe de evaluatie tool kan gebruiken

**Comment by BobvanElburg** [comment]
Website gevonden met documentatie. Documentatie doorgelezen en gemarkeerd op interessante onderdelen. Documentatie opgeslagen op Google drive van Urbinn. Bevindingen zijn gedocumenteerd en advies over het gebruik van de informatie is vastgelegd. Dit document is opgeslagen op de Google drive van Urbinn.
