### ISSUE TITLE
Github repo maken voor eigen ORB2 branch

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#53]
Repo is: https://github.com/urbinn/orb2

**Comment by chrisros** [comment]
Gekozen voor mogelijkheid 
Origin: ORB2
    * Branch voor OSX
    * Branch voor Ubuntu

Gevolg: Mogelijkheid voor cherry picking tussen branches, t.b.v. code-reuse.

**Comment by jvhoven** [comment]
De repository is nu gebaseerd op https://github.com/Alkaid-Benetnash/ORB_SLAM2, dit bevat de load/save map functionaliteit. Daarnaast is ervoor gekozen om alleen op de server het algoritme uit te voeren. Dit betekent dus dat we geen OS specifieke branches zullen aanmaken om het lokaal werkend te krijgen. 

Om wijzigingen in de code te testen dien je de repository te clonen in je home directory op de server. Daarna kan je het algoritme nogmaals compileren en vervolgens runnen met desbetreffende wijzigingen. 

De beschikbare datasets (voor nu TUM en KITTI) staan in `/data/urbinn/datasets`.
