### ISSUE TITLE
aanpakken die objecten herkennen op basis van photometric differences in stereo images

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#62]

**Comment by BobvanElburg** [comment]
onderzoek doen naar methodes die objecten kunnen herkennen op basis van photomatric differences en deze documenteren.

**Comment by Viradj** [comment]
https://drive.google.com/open?id=1bnR3CCtkBYiA48yCJLVQYKANvou0I734Oah5r_xmCxw
