### ISSUE TITLE
Evaluatie: aanpak pointcloud vs pointcloud

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#63]

**Comment by BobvanElburg** [comment]
Discussie begonnen met Daniello en Isa om te kijken naar mogelijkheden om de aanpak vast te stellen van de evaluatie methode. Mogelijk om te gebruiken is het opnieuw blijven afspelen van de video zodat het programma een moment ervaart dat er geen extra punten meer te herkennen zijn tegenover de ground truth. Het leggen van de plattegrond over de resultaten.

**Comment by IIsaku** [comment]
Document uitgewerkt voor de evaluatie van point clouds. Het document 'Issue 63 - Evaluatieplan point cloud' is te vinden in Google Drive onder de map Issues
