### ISSUE TITLE
Evaluatie implementatie: pointcloud vs pointcloud

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#64]
Python
* genereren png voor visuele check
* metrics uitrekent

- [x] Op basis van LiDAR
- [x] Op basis van dieptebeeld
- [x] Op basis van ZED mesh generatie

**Comment by chrisros** [comment]
uitloop verlenging 3x8 uur

**Comment by jvhoven** [comment]
**Op basis van LiDAR**
De LiDAR points per frame samenvoegen tot een point cloud gaat niet werken. Er is gekozen voor een per keyframe aanpak waarbij de punten van LiDAR voor desbetreffende frame vergeleken wordt met de punten van ORB_SLAM2 d.m.v het uitvoeren van een nearest neighbour algoritme. De test die we gemaakt hebben is te vinden onder `pointcloudeval/keyframe_conversion`.

---

Helaas hebben wij geen LiDAR tot onze beschikking omdat degene die we wilden gebruiken nogal gebrekkig in functionaliteit was,  zo was de range maar 5m en kon het maar op één niveau scannen. Deze methode valt dan ook bij deze af.

**Comment by jvhoven** [comment]
**Op basis van dieptebeeld**
Voor de tweede methode is er gekozen om aan de hand van de dieptebeelden een ground-truth op te zetten die we kunnen gebruiken om de pointcloud te evalueren. Hiervoor is een klein experiment opgezet die te vinden is in de jupyter omgeving onder `pointcloudeval/depth_map`. 

---

Het eerste probleem dat geobserveerd hebben is dat een gegenereerd dieptebeeld altijd relatief is. Dit zou dus inhouden dat als je vanaf een ander perspectief naar hetzelfde beeld kijkt, dat je een afwijkend dieptebeeld krijgt. Daarnaast is uit de test gebleken dat een dieptebeeld niet nauwkeurig genoeg is omdat het sommige vlakken niet kan identificeren en dus aanduidt als een standaard kleur. Deze methode valt dan ook bij deze af.

**Comment by IIsaku** [comment]
We hebben met de groep besproken dat het formeel evalueren van de kwaliteit van een point cloud niet gaat lukken met de middelen en kennis die wij hebben. We gaan de kwaliteit van een point cloud op informele basis beoordelen. Wel gaan we de kwaliteit van de 'estimated trajectory' die het ORB SLAM 2 algoritme genereert, formeel evalueren. Hiervoor wordt een nieuw issue aangemaakt.
