### ISSUE TITLE
YOLO uitproberen op KITTI

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#65]

**Comment by jeroenvuurens** [comment]
open source
darknet
retrained model downloaden

**Comment by chrisros** [comment]
Yolo9000 < TinyYOLO
Kittydata niet perfect ivm. monochrome foto's 
simpele setup


TiY: https://pjreddie.com/darknet/yolo/
Y9K: https://github.com/philipperemy/yolo-9000

**Comment by chrisros** [comment]
Toepassing van tinyyolo voor live on-premise object recognition https://medium.com/@xslittlegrass/almost-real-time-vehicle-detection-using-yolo-da0f016b43de

**Comment by chrisros** [comment]
http://cs231n.stanford.edu/reports/2016/pdfs/263_Report.pdf
Traffic Sign Detection using You Only Look Once Framework

**Comment by chrisros** [comment]
http://btsd.ethz.ch/shareddata/
Belgische dataset met verkeersborden
