### ISSUE TITLE
Tiny Yolo dataset uitzoeken

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#67]
Welke dataset is gebruikt om tiny yolo te trainen

**Comment by jeroenvuurens** [comment]
Ook welke ground truth is er en wat is de structuur van de ground truth.

**Comment by Viradj** [comment]
https://drive.google.com/open?id=1L6nBC2vJS8agwTbxwmjD5wNawMMyjdkUMtXPywSOS98
