### ISSUE TITLE
Tiny Yolo: uitzoeken hoe te trainen

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#68]
Opzoeken info over hoe het trainen van Tiny Yolo werkt, hoe snel het trainen is, op wat voor hardware.
Probeer uit op bestaande datasets met bestaande ground truth, niet meest optimale model maken, maar consequent het beste model na een bepaalde tijd trainen (bv 1 of 5 uur).

**Comment by jeroenvuurens** [comment]
wat voor parameters etc.

**Comment by jeroenvuurens** [comment]
Kijk ook naar mogelijkheid breedbeeld.
Ook herkennen kleine objecten.
herkennen gedeeltelijk zichtbare objecten.

**Comment by BobvanElburg** [comment]
Gevonden sources:
Forum vraag van iemand die tiny yolo probeert te trainen. Deze is beantwoord met links naar verscheidene pagina's om verder te komen.
https://groups.google.com/forum/#!topic/darknet/sw1iX2TYf0U

Hoe je Yolo kan trainen met Pascal VOC
https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data

GUI for marking bounded boxes of objects in images for training Yolo v2
https://github.com/AlexeyAB/Yolo_mark

Hier word een omschrijving gegeven over de werking van tiny yolo en hoe dit te draaien is op iOS.
http://machinethink.net/blog/object-detection-with-yolo/

Ik heb geen duidelijke informatie gevonden waarom de image een vaste grote moet hebben.

Informatie over het herkennen van kleinere objecten in een groter plaatje dat is geresized.
https://groups.google.com/forum/#!topic/darknet/dV38YzRiUqk

Informatie over het trainen van YOLOv2 op 'partial' objects.
https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/
Dit gaat voornamelijk over het zelf maken van een trainings set en mogelijk niet hetgeen wat we zoeken.

**Comment by BobvanElburg** [comment]
Gedocumenteerd en opgeslagen op de drive locatie "https://drive.google.com/drive/folders/0BwqKb57nYbXvbUVnX2ZqZ1lub3M"
