### ISSUE TITLE
KITTI point cloud resultaten

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#70]

**Comment by jeroenvuurens** [comment]
De bedoeling is dat op de server runs worden gedaan op delen van de KITII dataset en de pointclouds in .csv formaat worden bewaard op de server.

**Comment by Eyegi** [comment]
Running into build problems bin_Vocabulary not found

**Comment by Eyegi** [comment]
Committed to git.
Ran on server Map.csv created for seq 00
