### ISSUE TITLE
Resultaten ORB2 bin exporteren

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#72]
Op basis van de klassenbeschrijvingen, de huidige map niet saven als bin, maar als readable format (bv JSON) zodat de bin file in Python kan worden ingelezen. De conversie van bin naar JSON kun je in C++ doen, je kunt het ook in Python doen als dat makkelijker blijkt.

**Comment by jeroenvuurens** [comment]
XML formaat

**Comment by archdanny** [comment]
Methode SaveMapForXML in System gemaakt.
