### ISSUE TITLE
Literatuur scan: filteren slam met object detectie

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#81]
of object detectie icm point clouds (bv afstand objecten inschatten)

**Comment by archdanny** [comment]
2 papers gevonden. 

Paper 1 : Object Detection and Tracking in RGB-D SLAM via Hierarchical Feature Grouping.

Paper 2 : Monocular SLAM Supported Object Recognition.

Paper 1 sluit het beste aan onze setup (YOLO en ORB SLAM).

https://drive.google.com/open?id=0B_afORSfPeRYdUJGdzVmd1R3aDg
