### ISSUE TITLE
yolo training data verzamelen

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#82]
Uit kruistabel beschikbare datasets
belgische dataset
coco
kitti object 2d task

**Comment by jeroenvuurens** [comment]
Bestaande datasets
op server zetten

**Comment by jeroenvuurens** [comment]
optioneel niet ter zake doende frames (zonder objecten of typisch Amerikaanse verkeersborden) eruit halen.

**Comment by M4dmuffin** [comment]
alle datasets zijn op de server gezet

**Comment by chrisros** [comment]
Ontbreekt: http://btsd.ethz.ch/shareddata/
