### ISSUE TITLE
Vaststellen klassen voor trainen Yolo

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#83]
Kijken naar Kitti data, welke objecten worden door orb opgepikt die zinvol zijn om te classificeren.

**Comment by chrisros** [comment]
nader overleg

**Comment by M4dmuffin** [comment]
Document opgesteld samen met Jeroen. Zie -> https://docs.google.com/spreadsheets/d/1B9jabEJgo_CQKnJTPorHLHq5gcTB_onDxKndBN_Dj7I/edit#gid=0 voor alle huidige labels
