### ISSUE TITLE
Paper zoeken voor close reading sessie

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#87]
Over hoe je semantic map/slam kunt evalueren.

**Comment by NektariosEvangelou** [comment]
2 potentiële papers toegevoegd in google drive. Urbinn --> Documentatie/Papers --> Semantic Map Evaluation Papers.

**Comment by BobvanElburg** [comment]
Gezocht of er papers beschikbaar waren die pointclouds met elkaar gebruiken voor evaluatie. Papers van Nektarios gelezen en document 14-iser was een relevant en interessante paper om te gebruiken.
