### ISSUE TITLE
Opzoeken labeling tool

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#88]
Een tool waarmee gemakkelijk fotos kunnen worden gelabeld om daar vervolgens Yolo mee te trainen. Er is al een inventarisatie van datasets op drive, en een document waarin een mogelijke tool staat:
https://docs.google.com/document/d/1FH5rJF20N7l0dXtTWjQPEA127p6ZXFGgx78cieZz0wg/edit

**Comment by M4dmuffin** [comment]
redelijk stabiele label tool gevonden zie https://github.com/puzzledqs/BBox-Label-Tool
