### ISSUE TITLE
import xml data (pointcloud) orbslam2

### ISSUE THREAD

**Issue by chrisros** [urbinn/urbinn#89]
De import van een pointcloud middels xml realiseren

**Comment by jvhoven** [comment]
Blijkt meer werk als verwacht. Uren aangepast van 5 naar 8. Uren 3x verlengt.

**Comment by NektariosEvangelou** [comment]
ORB import is bijna werkend gekregen met stereo_kitti. We verlengen deze issue nogmaals met 8 uur.

**Comment by jvhoven** [comment]
Prioriteit ligt bij het fixen van de memory leaks; de uitkomst daarvan beïnvloedt deze issue.
