### ISSUE TITLE
trainen tiny YOLO maandag nacht

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#93]
- [x] Een short list ca. 20-40 klassen maken adhv #83
- [x] Kitti 2D Object Data set (train/test)
- [ ] Voor Darknet tiny yolo configureren
- [ ] Op CPU maandag nacht laten trainen

**Comment by jvhoven** [comment]
http://guanghan.info/blog/en/my-works/train-yolo/

**Comment by M4dmuffin** [comment]
Ondernomen stappen:

-Darknet Tiny-Yolo geprobeerd te runnen, zonder resultaat. Tritanium (server leiden) zijn de GPU niet beschikbaar (waarschijnlijk werkzaamheden). 

-Darknet geeft een GPU CUDA error tijdens de training. Dit is een recente error die vooralsnog niet opgelost is.

-Overleg met Jeroen overstap gemaakt naar Darkflow.

-Darkflow geinstalled. 

-KITTI dataset heeft niet veel klasses, aantal klassen staan nu op 4 ipv de aangegeven  20/40 klassen in de issue. Dit is gedaan om alsnog voor maandag nacht te kunnen trainen.

-De annotations moeten een ander formaat hebben in Darkflow. Dit kan gedaan worden met BBox-labeltool script.

**Comment by jeroenvuurens** [comment]
Alternatief is eventueel zelf tiny YOLO v2 in Tensorflow namaken?

 Dat hoeft niet zoveel werk te zijn:
- Ik heb een notebook gemaakt met een implementatie van een 3x3 LeNet model, dat lijkt erg veel op de basis structuur van YOLO, is alleen minder diep.
- YOLO staat op diverse plekken beschreven:
  - http://cs229.stanford.edu/proj2016/report/BuhlerLambertVilim-CS229FinalProjectReport.pdf
  - code voor tensorflow yolo architecture (alleen geen training) https://github.com/gliese581gg/YOLO_tensorflow/blob/master/YOLO_tiny_tf.py
  - alleen beschrijving tiny yolo v2 http://machinethink.net/blog/object-detection-with-yolo/
  - https://leonardoaraujosantos.gitbooks.io/artificial-inteligence/content/single-shot-detectors/yolo.html

**Comment by jeroenvuurens** [comment]
het trainen vannacht lijkt goed te zijn gegaan. Het duurde ca. 2 ur om tot 10000 batches te komen, daarna aantal batches verhoogd en verder geleerd vanaf 10000 met het commando:
./cnn detector train cfg/kitti.data cfg/tiny-yolo-kitti.cfg -gpus 0 kitti/tiny-yolo-kitti_10000.weights

Vanochtend stopgezet nadat weights 70000 was weggeschreven (na ca. 18M images), en gekopieerd naar darknet/kitti/tiny-yolo-kitti_final. Aan de trainingsresultaten te zien lijkt de avg recall (%gelabelde objecten dat herkend wordt) ca. 50%.

Paar aantekeningen:
- ik heb darknet gerenamed naar cnn (darknet als procesname ziet er wat verdacht uit op iemand anders cluster)
- de labels voor kitti zijn omgezet met het script in notebook urbinn/yolo_gt_eval/convert_labels_files.ipynb op ADS server
- de label .txt files heb ik op tritanium in dezelfde folder gezet als de plaatjes, anders kan darknet ze niet vinden
- ik heb de cfg aangepast naar 1242x375 omdat die afmetingen ook zijn gebruikt bij het omzetten van de labels

**Comment by jeroenvuurens** [comment]
todo: checken of we het retrained model kunnen gebruiken. Is op tritanium nog niet gelukt, maar je hebt daarvoor de getrainde weights en de cfg file nodig.

Note: copieren van files kun je denk ik alleen van tritanium naar ADS server, bv met scp:
scp <file> jeroen@datascience.hhs.nl:.

heb cfg en weight in /data/urbinn/yolo-kitti gezet op ads server

**Comment by jeroenvuurens** [comment]
Op tritanium kunnen we momenteel geen images testen, reden:
- cuda drivers zijn ouder (cudnn5), waardoor yolo alleen een oudere yolo versie compiled
- de getrainde weights lijken goed te zijn
- evaluatie moet voor nu op eigen server met recente yolo worden uitgevoerd.

maandag 13 nov worden de CUDA drivers op tritanium geüpdatet  (Cuba 8.0 of 9.0 met hopelijk cudnn6), dan kunnen we de test daar ook snel doen.

**Comment by chrisros** [comment]
Op Tritanium kunnen we images trainen, bovenstaande reden lijkt niet waar.

**Comment by jeroenvuurens** [comment]
Idd, het trainen en testen lukt nu met de laatste versie van darknet, staat op tritanium in ~/darknet
Paar aantekeningen:
- in de cfg kun je 5 anchors invullen, als ik het goed begrijp zijn dat de meest voorkomende height/width afmetingen. Heb in darknet/python een script gedownload om de anchor te berekenen over de trainingsset: py python/gen_anchors.py -filelist /local/vuurensj/data/kitti/training2.txt -output_dir generated_anchors/voc-reproduce -num_clusters 5
- in de cfg kun je het aantal klassen aanpassen, maar dan moet je het aantal filters van de laatste layer aanpassen naar (#classes+5)*5
- het testen van images werkt alleen goed als in de cfg batch=1 en subdivision=1 staat. Omdat dat langzamer traint staat er een aparte cfg voor het testen.

**Comment by jeroenvuurens** [comment]
staat nu te draaien om model te leren met 7 classes, aangepaste anchors. cfg is kitti-2, output staat in darknet/kitti2
