### ISSUE TITLE
Dieptebeeld genereren slinger

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#94]
na #91
- [x] Zed library installeren met cuda
- [ ] maak een mesh beeld van opnamen
NB indien nodig nieuwe opnames maken

**Comment by Viradj** [comment]
Doc: https://drive.google.com/open?id=1qt1W-VjeEcUBZHD9yZwrUA_uoQYuUizhXUSca9ih_9w

Voor de ORB test kan gebruik worden gemaakt van de dataset : slinger_rugzak_2017_10_02

In afwachting van ORB-SLAM voor het tweede deel van de ticket.
