### ISSUE TITLE
evaluatie self trained YOLO kitti GT

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#97]

**Comment by chrisros** [comment]
Lijkt geen GT te zijn van de test datasets van kitti

**Comment by jeroenvuurens** [comment]
Heb KITTI opnieuw aangezet.
In de ~/darknet folder staat een file kitti1811.readme met de beschrijving. Datafiles staan in /local/vuurensj/kitti1811 en op een soortgelijke manier hebben alle files de naam kitti1811. Het is dezelfde tiny yolo config als de vorige keer. Zit nu op 210k iteraties, zal morgen bij 250k stoppen.

**Comment by chrisros** [comment]
""" kitti1811_validate results """
YOLO_JSON: /data/urbinn/datasets/kitti1811/kitti1811_validate/objects.json
KITTI_GT: /data/urbinn/datasets/training_validation/kitti2/{}
IOU Treshold: 0.4

Checking 980 images...
Compares:           31763 
Detected BB's:      4608
GroundTruth BB's:   5017
False positives:    2127
percentage of boundingboxes that where detected:             % 91.85
percentage of boundingboxes that where falsely detected:     % 46.16
net percentage of boundingboxes that where detected correct: % 45.69
evaluate took 155.027 ms

**Comment by chrisros** [comment]
Door de 'geshifte'  boxes lijkt het 'false positive' getal hoeger te liggen dan het waarschijnlijk is, vooral de kleine boxes (10x10 px) zijn erg makkelijk te missen, een idee is alle boxes 10px naar links en boven te shiften (Alle coordinaten -10) om te kijken of het false positive getal dan afneemt.

**Comment by chrisros** [comment]
Verder is het wel positief om te zien dat, puur kijkend naar kwantiteit 90% van de GT wordt herkend.

**Comment by jeroenvuurens** [comment]
Die 91.85% is denk ik #detected/#groundtruth? Omdat daar de false positives in zitten is dat geen goede manier om te vergelijken.
45% is denk ik werkbaar. Mogelijk worden de resultaten beter als we betere trainingslabels gebruiken.

**Comment by chrisros** [comment]
Image width: 
Image height: 
Debug mode? [y/N]:
Match classes mode? [y/N]:
Old style bounding box notation? [y/N]:
IOU Treshold [0.0-1.0]: .4
YOLO_JSON: /data/urbinn/datasets/kitti1811/kitti1811_validate/objects.json
KITTI_GT: /data/urbinn/datasets/training_validation/kitti2/{}
IOU Treshold: 0.4

Checking 980 images...
Compares:                    31763 
Detected BB's:            4608
GroundTruth BB's:    5017
False positives:           590
percentage of boundingboxes that where detected:                           % 91.85
percentage of boundingboxes that where falsely detected:             % 12.80
net percentage of boundingboxes that where detected correct:    % 79.04
evaluate took 154.708 ms

**Comment by chrisros** [comment]
Bovenstaand zijn de reseultaten als ik de boundingboxen van yolo (-12, -12) transleer

**Comment by chrisros** [comment]
de resultaten van deze yolo run (images) zijn te vinden in 
datascience:  /data/urbinn/datasets/kitti1811/translated_10px/
