### ISSUE TITLE
YOLO config file beschrijven

### ISSUE THREAD

**Issue by jeroenvuurens** [urbinn/urbinn#98]
alle parameters uit de yolo config file uitzoeken en in een document beschrijven

**Comment by NektariosEvangelou** [comment]
Zo ver mogelijk de beschrijving van de tiny-yolo.cfg gemaakt. Deze is terug te vinden in de google drive: https://docs.google.com/spreadsheets/d/1RhoRehhnOIf51xIWjCnmzzTG-EcZXrQ90k7fAwQILcM/edit#gid=0
